version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/strands-py"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "ci(python)"
    groups:
      dev-dependencies:
        patterns:
          - "pytest"
  - package-ecosystem: "npm"
    directory: "/site"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "ci(docs)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: ci
