"""Auto-generated by bindgen. Do not edit."""
# ruff: noqa: E501, F401, I001
# fmt: off

from __future__ import annotations

from typing import Any

from wasmtime.component import Variant as _WitVariant

from .strands_agent.api import Agent, AgentConfig, AgentError, AgentIdentity, AttributeValue, ConcurrentOptions, EventStream, InvokeArgs, RespondArgs, ResponseStream, ToolExecutorStrategy, TraceAttribute, TraceContext
from .strands_agent.conversation import ConversationManagerConfig, SlidingWindowConversationManager, SummarizingConversationManager
from .strands_agent.edge_handler_registry import EdgeHandlerError, HandlerState
from .strands_agent.elicitation_handler import ElicitAction, ElicitRequest, ElicitResponse, ElicitationError
from .strands_agent.host_log import LogEntry, LogLevel
from .strands_agent.mcp import EnvVar, HttpHeader, HttpTransport, McpClientConfig, McpConnectionState, McpTransport, SseTransport, StdioTransport, TasksConfig
from .strands_agent.messages import CacheKind, CachePointBlock, Citation, CitationLocation, CitationText, CitationsBlock, ContentBlock, DocumentBlock, DocumentCitationsConfig, DocumentRange, DocumentSource, GuardContentBlock, GuardContentImage, GuardContentText, GuardQualifier, ImageBlock, ImageSource, InterruptResponseBlock, JsonBlock, Message, MessageMetadata, Metrics, PromptInput, ReasoningBlock, Role, S3Location, SearchResultRange, TextBlock, ToolResultBlock, ToolResultContent, ToolResultStatus, ToolUseBlock, Usage, VideoBlock, VideoSource, WebLocation
from .strands_agent.model_provider import CountTokensArgs, ModelEventStream, ModelStreamOptions, StartStreamArgs
from .strands_agent.models import AnthropicModel, BedrockModel, CustomModel, GoogleModel, ModelConfig, ModelError, ModelParams, OpenaiModel
from .strands_agent.multi_agent import AgentNode, EdgeConfig, EdgeHandler, GraphConfig, HandoffEvent, MultiAgentInvokeArgs, MultiAgentNode, MultiAgentResult, MultiAgentStreamEvent, NodeConfig, NodeError, NodeEventData, NodeKind, NodeResult, NodeStartData, OrchestrationStatus, SwarmConfig, TerminalStatus
from .strands_agent.retry import BackoffStrategy, ConstantBackoff, ExponentialBackoff, JitterKind, LinearBackoff, ModelRetryStrategy, RetryConfig
from .strands_agent.sessions import ConversationManagerState, CustomStorage, FileStorage, PluginStateEntry, RetryStrategyState, S3Storage, SaveLatestPolicy, SessionManager, SlidingWindowState, Snapshot, SnapshotData, SnapshotLocation, SnapshotManifest, SnapshotScope, StorageConfig, StorageError, SummarizingState
from .strands_agent.snapshot_storage import DeleteSessionArgs, ListSnapshotIdsArgs, LoadSnapshotArgs, ManifestArgs, SaveManifestArgs, SaveSnapshotArgs
from .strands_agent.snapshot_trigger_handler import TriggerError, TriggerParams
from .strands_agent.streaming import AfterInvocationData, AfterModelCallData, AfterToolCallData, AgentLoopMetrics, AgentMetrics, AgentResultData, AgentTrace, BeforeInvocationData, BeforeModelCallData, BeforeToolCallData, ContentBlockData, HookRedaction, InputRedaction, Interrupt, InvocationMetrics, MessageAddedData, MetadataEvent, ModelMessageData, ModelStopData, ModelStreamUpdateData, OutputRedaction, RedactionEvent, StopEvent, StopReason, StreamError, StreamEvent, ToolMetrics, ToolResultData, ToolStreamUpdateData, ToolUseData, ToolsBatchData, TraceMetadataEntry
from .strands_agent.tools import AgentAsToolConfig, CallToolArgs, ToolChoice, ToolError, ToolEventStream, ToolSpec, ToolStreamEvent
from .strands_agent.vended import AgentSkills, BashTool, ContextOffloader, FileEditorTool, HttpRequestTool, NotebookTool, SkillSource, VendedPlugin, VendedTool
from .wasi_clocks.monotonic_clock import Duration, Instant
from .wasi_clocks.wall_clock import Datetime
from .wasi_io.error import Error
from .wasi_io.poll import Pollable
from .wasi_io.streams import InputStream, OutputStream


def ok(value: Any = None) -> _WitVariant:
    """Wrap ``value`` as the ``ok`` arm of a ``result<T, E>``."""
    return _WitVariant("ok", value)


def err(value: Any = None) -> _WitVariant:
    """Wrap ``value`` as the ``err`` arm of a ``result<T, E>``."""
    return _WitVariant("err", value)


__all__ = [
    'AfterInvocationData',
    'AfterModelCallData',
    'AfterToolCallData',
    'Agent',
    'AgentAsToolConfig',
    'AgentConfig',
    'AgentError',
    'AgentIdentity',
    'AgentLoopMetrics',
    'AgentMetrics',
    'AgentNode',
    'AgentResultData',
    'AgentSkills',
    'AgentTrace',
    'AnthropicModel',
    'AttributeValue',
    'BackoffStrategy',
    'BashTool',
    'BedrockModel',
    'BeforeInvocationData',
    'BeforeModelCallData',
    'BeforeToolCallData',
    'CacheKind',
    'CachePointBlock',
    'CallToolArgs',
    'Citation',
    'CitationLocation',
    'CitationText',
    'CitationsBlock',
    'ConcurrentOptions',
    'ConstantBackoff',
    'ContentBlock',
    'ContentBlockData',
    'ContextOffloader',
    'ConversationManagerConfig',
    'ConversationManagerState',
    'CountTokensArgs',
    'CustomModel',
    'CustomStorage',
    'Datetime',
    'DeleteSessionArgs',
    'DocumentBlock',
    'DocumentCitationsConfig',
    'DocumentRange',
    'DocumentSource',
    'Duration',
    'EdgeConfig',
    'EdgeHandler',
    'EdgeHandlerError',
    'ElicitAction',
    'ElicitRequest',
    'ElicitResponse',
    'ElicitationError',
    'EnvVar',
    'Error',
    'EventStream',
    'ExponentialBackoff',
    'FileEditorTool',
    'FileStorage',
    'GoogleModel',
    'GraphConfig',
    'GuardContentBlock',
    'GuardContentImage',
    'GuardContentText',
    'GuardQualifier',
    'HandlerState',
    'HandoffEvent',
    'HookRedaction',
    'HttpHeader',
    'HttpRequestTool',
    'HttpTransport',
    'ImageBlock',
    'ImageSource',
    'InputRedaction',
    'InputStream',
    'Instant',
    'Interrupt',
    'InterruptResponseBlock',
    'InvocationMetrics',
    'InvokeArgs',
    'JitterKind',
    'JsonBlock',
    'LinearBackoff',
    'ListSnapshotIdsArgs',
    'LoadSnapshotArgs',
    'LogEntry',
    'LogLevel',
    'ManifestArgs',
    'McpClientConfig',
    'McpConnectionState',
    'McpTransport',
    'Message',
    'MessageAddedData',
    'MessageMetadata',
    'MetadataEvent',
    'Metrics',
    'ModelConfig',
    'ModelError',
    'ModelEventStream',
    'ModelMessageData',
    'ModelParams',
    'ModelRetryStrategy',
    'ModelStopData',
    'ModelStreamOptions',
    'ModelStreamUpdateData',
    'MultiAgentInvokeArgs',
    'MultiAgentNode',
    'MultiAgentResult',
    'MultiAgentStreamEvent',
    'NodeConfig',
    'NodeError',
    'NodeEventData',
    'NodeKind',
    'NodeResult',
    'NodeStartData',
    'NotebookTool',
    'OpenaiModel',
    'OrchestrationStatus',
    'OutputRedaction',
    'OutputStream',
    'PluginStateEntry',
    'Pollable',
    'PromptInput',
    'ReasoningBlock',
    'RedactionEvent',
    'RespondArgs',
    'ResponseStream',
    'RetryConfig',
    'RetryStrategyState',
    'Role',
    'S3Location',
    'S3Storage',
    'SaveLatestPolicy',
    'SaveManifestArgs',
    'SaveSnapshotArgs',
    'SearchResultRange',
    'SessionManager',
    'SkillSource',
    'SlidingWindowConversationManager',
    'SlidingWindowState',
    'Snapshot',
    'SnapshotData',
    'SnapshotLocation',
    'SnapshotManifest',
    'SnapshotScope',
    'SseTransport',
    'StartStreamArgs',
    'StdioTransport',
    'StopEvent',
    'StopReason',
    'StorageConfig',
    'StorageError',
    'StreamError',
    'StreamEvent',
    'SummarizingConversationManager',
    'SummarizingState',
    'SwarmConfig',
    'TasksConfig',
    'TerminalStatus',
    'TextBlock',
    'ToolChoice',
    'ToolError',
    'ToolEventStream',
    'ToolExecutorStrategy',
    'ToolMetrics',
    'ToolResultBlock',
    'ToolResultContent',
    'ToolResultData',
    'ToolResultStatus',
    'ToolSpec',
    'ToolStreamEvent',
    'ToolStreamUpdateData',
    'ToolUseBlock',
    'ToolUseData',
    'ToolsBatchData',
    'TraceAttribute',
    'TraceContext',
    'TraceMetadataEntry',
    'TriggerError',
    'TriggerParams',
    'Usage',
    'VendedPlugin',
    'VendedTool',
    'VideoBlock',
    'VideoSource',
    'WebLocation',
    'err',
    'ok',
]
